### ISSUE TITLE
Code review

### ISSUE THREAD

**Issue by SarvarKh** [Byabasaija/Concert-page-Capstone-Project#2]
If you have any comments, please leave them below

**Comment by Andrik27001** [comment]
The project looks very good, I just have some recommendations to make it better:
- Try to use less Bootstrap, that was a requirement for this capstone
- Check the indentation of your code
- You can fix that first image when you press the "MORE" button on mobile
- Adjust the border of the button on the mobile navbar.

**Comment by SarvarKh** [comment]
**The project looks nice and clean.**
Here is my only suggestion you may consider:
- using background text for your main html in the 1st page.

**Comment by apricot12** [comment]
**On the whole it looks very good, but try to do the following:**

- In the About page, try to square the concert images.

- On the desktop site, try to make the ticket box, and room selection box smaller.

- Could've tried to add partner brand logos in the about page as per the original design specs.

**Comment by akshay-narkar** [comment]
**Project looks great!** 

1) Can fix the section below the more tab
